#!/usr/bin/env bash

# WebBroboard --- Clipboard as a WebBrowser

# Copyright (C) 2017, 2024 Wojciech Siewierski

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    echo -n "$@" | wl-copy
else
    echo -n "$@" | xsel --input --primary
    echo -n "$@" | xsel --input --clipboard
fi

notify-send --app-name WebBroboard WebBroboard "$*"
